function u1 = mydialog(x1)
    global Rnum;
    global Rend;

    u1 = x1;
    
    if u1==0
    d = dialog('Position',[300 300 250 150],'Name','안내 창');

    txt = uicontrol('Parent',d,...
               'Style','text',...
               'Position',[20 80 210 40],...
               'String','회전방향 선택 후 버튼을 실행하세요.');

    btn = uicontrol('Parent',d,...
               'Position',[85 20 70 25],...
               'String','확인',...
               'Callback','delete(gcf)');
    end
    
    if u1==1
    d = dialog('Position',[300 300 250 150],'Name','안내 창');

    txt = uicontrol('Parent',d,...
               'Style','text',...
               'Position',[20 80 210 40],...
               'String','회전수 입력 후 버튼을 실행하세요.');

    btn = uicontrol('Parent',d,...
               'Position',[85 20 70 25],...
               'String','확인',...
               'Callback','delete(gcf)');
    end
    if u1==2
    d = dialog('Position',[300 300 250 150],'Name','안내 창');

    txt = uicontrol('Parent',d,...
               'Style','text',...
               'Position',[20 80 210 40],...
               'String','회전수는 1회 이상으로 입력해야 합니다.');

    btn = uicontrol('Parent',d,...
               'Position',[85 20 70 25],...
               'String','확인',...
               'Callback','delete(gcf)');
    end
    
    if u1==3
  
    Rend = num2str(Rend);
    message = sprintf('알고리즘에 사용된 회전 수 : %d\n총 걸린 시간 : %s', Rnum, Rend);
    d = dialog('Position',[400 400 250 150],'Name','결과 창');

    txt = uicontrol('Parent',d,...
               'Style','text',...
               'Position',[40 90 210 40],...
               'String',message,'FontSize',10);

    btn = uicontrol('Parent',d,...
               'Position',[85 20 70 25],...
               'String','확인',...
               'Callback','delete(gcf)');
    end
end